import Head from "next/head";
import Image from "next/image";
import { Carousel } from "react-responsive-carousel";
import styles from "../styles/Home.module.css";

const images = [
  "92c952",
  "771796",
  "24f355",
  "d32776",
  "f66b97",
  "56a8c2",
  "b0f7cc",
  "54176f",
  "51aa97",
  "810b14",
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Carousel Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.slideContainer}>
          <Carousel showThumbs={false}>
            {images.map((url, index) => (
              <div key={url}>
                <Image
                  alt=""
                  src={`https://via.placeholder.com/600/${url}`}
                  width={640}
                  height={600}
                />
                <p className="legend">Image {index + 1}</p>
              </div>
            ))}
          </Carousel>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
