import Head from "next/head";
import Image from "next/image";
import { Carousel } from "react-responsive-carousel";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Carousel Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.slideContainer}>
          <Carousel showThumbs={false}>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-1.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 1</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-2.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 2</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-3.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 3</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-4.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 4</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-5.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 5</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-6.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 6</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-7.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 7</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-8.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 8</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-9.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 9</p>
            </div>
            <div>
              <Image
                alt=""
                src="http://lorempixel.com/output/cats-q-c-640-480-10.jpg"
                width={640}
                height={480}
              />
              <p className="legend">Cat 10</p>
            </div>
          </Carousel>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
